name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main  # Menjalankan workflow ketika ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Menjalankan di runner GitHub Actions berbasis Ubuntu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}  # Menambahkan session token
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create EC2 Instance
        id: ec2_create
        run: |
          # Membuat instance EC2 menggunakan AWS CLI
          INSTANCE_ID=$(aws ec2 run-instances --image-id ami-0df8c184d5f6ae949 --count 1 --instance-type t2.micro --key-name vockey --security-group-ids sg-0c6a6f87a7620e211 --subnet-id subnet-0a367105a13b51288 --user-data file://.github/workflows/bashcript.sh --query "Instances[0].InstanceId" --output text)
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
        
      - name: Wait for EC2 Instance to be Running
        run: |
          aws ec2 wait instance-running --instance-ids $INSTANCE_ID

      - name: Get Public IP of EC2 Instance
        id: ec2_ip
        run: |
          PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
          
